name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events for any main branch
  push:
    branches-ignore:    
      - 'gh-pages'
  pull_request:
  workflow_dispatch:

env:
  gh_build: false
  fhir_build: true

jobs:
  # This workflow contains two jobs: one to call the GH build, one to call the FHIR build
  call-gh-build: 
    if: ${{ fromJson(env.gh_build) }}
    uses: costateixeira/fhir-ig-actions/.github/workflows/gh-ci-build.yaml@main
  call-fhir-build: 
    if: ${{ fromJson(env.fhir_build) }}
    uses: costateixeira/fhir-ig-actions/.github/workflows/fhir-ci-build.yaml@main
