name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events for any main branch
  push:
    branches-ignore:    
      - 'gh-pages'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: GH build
        if: ${{ true }} # Update this hardcoded value to enable/disable GH build
        uses: costateixeira/fhir-ig-actions/.github/workflows/gh-ci-build.yaml@main
      - name: FHIR build
        if: ${{ false }} # Update this hardcoded value to enable/disable FHIR build
        uses: costateixeira/fhir-ig-actions/.github/workflows/fhir-ci-build.yaml@main
