name: CI

on:
  # Triggers the workflow on push or pull request events for any main branch
  push:
    branches-ignore:    
      - 'gh-pages'
  pull_request:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:   
    - name: Debug clone URL
      run: echo "Clone URL is ${{ github.event.pull_request.head.repo.clone_url }}"



  call-gh-build:
    if: ${{ true }} # Update this hardcoded value to enable/disable GH build
    uses: costateixeira/fhir-ig-actions/.github/workflows/gh-ci-build.yaml@main
  call-fhir-build:
    if: ${{ false }} # Update this hardcoded value to enable/disable FHIR build
    uses: costateixeira/fhir-ig-actions/.github/workflows/fhir-ci-build.yaml@main
