name: CI

on:
  push:
    branches-ignore:    
      - 'gh-pages'
  pull_request:
  workflow_dispatch:

jobs:
  call-gh-build:
    if: ${{ true }} # Update this hardcoded value to enable/disable GH build
    uses: costateixeira/fhir-ig-actions/.github/workflows/gh-ci-build.yaml@main
  call-fhir-build:
    if: ${{ false }} # Update this hardcoded value to enable/disable FHIR build
    uses: costateixeira/fhir-ig-actions/.github/workflows/fhir-ci-build.yaml@main
